[package]
name = "app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_main"
path = "src/test_main.rs"

[dependencies]
aster-time = { path = "../crates/aster-time" }
component = { path = "../crates/component" }
ostd = { path = "../crates/ostd" }
test-load-store = { path = "../crates/test-load-store" }